def tulosta_lentokone:
    print("   ⣖⠲⡀              ⢸⠉⡇")
    print("   ⠸⡆⠹⡀⣠⢤⡄          ⡏ ⡧⢤⡄")
    print("    ⡧⢄⣹⣅⣜⡀         ⢸⠁ ⢹⠚⠃")
    print(" ⣀⠴⢒⣉⡹⣶⣤⣀⡉⠉⠒⠒⠒⠤⠤⣀⣀⣀⠇  ⢸⠠⣄")
    print(" ⠈⠉⠁   ⠉⠒⠯⣟⣲⠦⣤⣀⡀  ⠈⠉⠉⠉⠛⠒⠻⢥⣀")
    print("           ⠈⠙⣲⡬⠭⠿⢷⣦⣤⢄⣀  ⠚⠛⠛⠓⢦⡀")
    print("       ⢀⣀⠤⠴⠚⠉⠁    ⣀⣉⡽⣕⣯⡉⠉⠉⠑⢒⣒⡾")
    print("  ⣀⡠⠴⠒⠉⠉ ⢀⣀⣀⠤⡤⢶⣶⣋⠉⠉   ⠈⠉⠉⠉⠉⠉⠁")
    print("⣖⣉⣁⣠⠤⠶⡶⡶⢍⡉   ⠙⠒⠯⠜")
    print(" ⠁    ⠑⢦⣯⠇")
def tulosta_viikatemies():
    print("          ⢀⣴⡆")
    print("     ⢀⣶⣆⢀⠔⠁ ⣷")
    print("     ⠚⣿⣿⣷⡄  ⢸")
    print("     ⣠⣺⣿⣿⡇  ⠸")
    print("    ⡸⣿⣿⣿⣿⡇")
    print("   ⡔⠁⢸⣿⣿⣿⣿")
    print("  ⠌   ⣿⣿⣿⣿")
    print(" ⡌    ⢸⣿⣿⣿⡇")
    print("⠈     ⢸⣿⣿⣿⡇")
    print("      ⣾⣿⣿⣿⣷")
    print("      ⣿⣿⣿⣿⣿⣷⣄")
    print("      ⠛⠛⠛⠛⠛⠛⠉")