def tulosta_viikatemies():
    print("          ⢀⣴⡆")
    print("     ⢀⣶⣆⢀⠔⠁ ⣷")
    print("     ⠚⣿⣿⣷⡄  ⢸")
    print("     ⣠⣺⣿⣿⡇  ⠸")
    print("    ⡸⣿⣿⣿⣿⡇")
    print("   ⡔⠁⢸⣿⣿⣿⣿")
    print("  ⠌   ⣿⣿⣿⣿")
    print(" ⡌    ⢸⣿⣿⣿⡇")
    print("⠈     ⢸⣿⣿⣿⡇")
    print("      ⣾⣿⣿⣿⣷")
    print("      ⣿⣿⣿⣿⣿⣷⣄")
    print("      ⠛⠛⠛⠛⠛⠛⠉")
tulosta_viikatemies()